[package]
name = "sdtest"
version = "0.1.0"
authors = ["W.J. van der Laan <laanwj@protonmail.com>"]
edition = "2018"

[dependencies]
nb = "0.1.1"
riscv-rt = "0.7"
k210-hal = "0.2.0"
riscv = "0.5"
k210-shared = { path = "../k210-shared" }
rcore-fs = { git = "https://github.com/rcore-os/rcore-fs" }
buddy_system_allocator = "0.3.9"
